name = "haroin-pv"
main = "src/pv-worker.ts"
compatibility_date = "2025-12-02"

[[kv_namespaces]]
binding = "HAROIN_PV"
id = "186445ba0495498facbca1e8c5c67bcc"

[[r2_buckets]]
binding = "CMS_IMAGES"
bucket_name = "haroin-cms-images"
